### ISSUE TITLE
What was it like to learn Dart?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/dart#199]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Dart? What was helpful while learning Dart? What did you struggle with? How did you tackle problems?
1. In what ways did Dart differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Dart :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by Stargator** [comment]
> How was your experience learning Dart? What was helpful while learning Dart? What did you struggle with? How did you tackle problems?

My experience learning Dart was good. I was curious about the language after my team discussed the possibility of migrating from AngularJS to AngularDart.

It was very helpful there was a tutorial on the AngularDart website. A lot of the concepts and structures are similar to Java, but since it was created more recently included things I wasn't familiar with like `=>` arrow syntax, Runes, and Sets (vs. Lists or Maps).

Dart finally informed me how a Set differed from an Array or Map in a more memorable way than 4 years of CompSci. Possibly because I'm using it in my code and back then I didn't have a real need for it.

I struggle with Runes, it's hard for me to conceptualize when to use it and other possibly uses. There are other concepts but I haven't needed to touch them, so they could be overwhelming or simple: Generics, Generators, Isolates, Typedefs, and Mixins

> In what ways did Dart differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

It felt very similar or Java (my original language) and I had been using JavaScript for years, so I actually felt relief using it over JavaScript. What was hard to learn was the API for the various types like Map, List, Set, String, num, int, double, and bool. Some of them had built-in functions and I still need to stretch myself to use them versus building out the logic myself.

Cascade notation was new to me, so I had to learn that, plus some of the operators like [Conditional member access](https://dart.dev/guides/language/language-tour#other-operators). Plus shorthand logic like `String determination = isFull() ? somethingGood() : somethingBad();

Concepts that carried over was the fact that Dart isn't strict about one class per file, so it allows for easier experimentation and scripting than Java. Additionally, having a VM and a clear and consistent type system was fantastic.

The last cherry on top is the need for less configuration. Development configuration and test configuration are more tightly connected than JavaScript, where you would need to configure your build system for development/production, but then configure in your test docs what are source files versus test files.

**Comment by Stargator** [comment]
@exercism/dart For any folks willing to provide input.

**Comment by md-weber** [comment]
I was working already in Angular with TypeScript, and the Dart Framework felt immediately familiar without any further work. Something I had struggled with was the work with Mixins and abstract classes.  

The documentation of Dart is also unique because it is one huge page that contains all the information. That lead to the problem that I avoided the documentation of dart in the beginning.
https://dart.dev/guides/language/language-tour

My main reasons for a change to dart have been the type system. That is something that JavaScript is just missing, and all frameworks and supersets (TypeScript) share the problem that you do not have to be consistent about them.

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
