### ISSUE TITLE
Unit tests all marked to skip (except one) on resistor-color exercise

### ISSUE THREAD

**Issue by bsene** [exercism/dart#200]
Hello all,

Maybe this issue is irrelevant , but i'm doing currently `resistor-color`exercise.

When I  ran the first time tests, all passed, as it came surprise to me I looked into the test file (eg: resistor_color_test.dart) and saw that all tests had skipped.

Does it the excepted behavior by the author(s) ? as it make this exercise too easy (eg: just define a method witch return 0 make pass the first test)

Regards,

**Comment by Stargator** [comment]
Hey @bsene, that is the expected behavior.

Ideally, the user/student would resolve the first test, then either gradually introduce the next test until all the tests are executed (**not** skipped). Or they could just enable all the tests to run and solve the issues in whatever order they please.

This mirrors [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development#Test-driven_development_cycle), which allows the user to gradually solve one part of the problem at a time.

Does that help answer your question?

**Comment by bsene** [comment]
Hello ok its now clear for me.
Thanks for the quick answer.
