### ISSUE TITLE
dart fix is removing import in test suite

### ISSUE THREAD

**Issue by kytrinyx** [exercism/dart#418]
Right now on `main`, if I run `dart fix --apply` to the isbn-verifier test suite, it removes the import as being unused.

```
$ dart fix --apply exercises/practice/isbn-verifier/test/isbn_verifier_test.dart 
Computing fixes in isbn_verifier_test.dart... 5.3s
Applying fixes...                      0.0s

isbn_verifier_test.dart
  unused_import • 1 fix

1 fix made in 1 file.
```

This happens even if I remove the `unused_import` rule in the `isbn-verifier/analysis_options.yaml` file.

Is this because the `isbn_verifier/isbn_verifier.dart` package is not implemented?

Is there a way to run `dart fix --apply` to order the imports correctly without removing unused imports?

**Comment by Stargator** [comment]
Yeah that is why I prefer having it defined in the template and not running linting on the file. I forgot about that until you posted this.

Because the given import may not have the implementations needed by the test suite. So it's not using anything from it it will be considered an unused import.

For that is why in the create exercise script we order the imports programmatically

**Comment by devkabiir** [comment]
I think a good course of action here would be to change the severity from `error` to `ignore` (severity of `warning` has the same effect). Since dart is not an interpreted language, there are no side effects of imports. This lint has existed since dart 1 days. Dart 2 is much more stricter and tree-shaking is built-in the compiler. The lint does not offer as much benefit as it's perceived to be.

```diff 
-    unused_import:         error
+    unused_import:         ignore
```

The above change needs to happen in `exercises/practice/isbn-verifier/analysis_options.yaml`.
Making the above change, and running `dart fix --apply` will not remove the unused import.
When you run `dart fix --apply` you need to be in `exercises/practice/isbn-verifier` directory.

If you run it from the top-level dir of the repository, it will pick up the top-level `analysis_options.yaml` and it will assume the top-level `pubspec.yaml`.

Generally when working with an exercise you'd want to make sure dart toolchain has it's cwd set to that exercise. Every exercise is an isolated dart package.

**Comment by Stargator** [comment]
> The above change needs to happen in `exercises/practice/isbn-verifier/analysis_options.yaml`. Making the above change, and running `dart fix --apply` will not remove the unused import. When you run `dart fix --apply` you need to be in `exercises/practice/isbn-verifier` directory.
> 
> If you run it from the top-level dir of the repository, it will pick up the top-level `analysis_options.yaml` and it will assume the top-level `pubspec.yaml`.
> 
> Generally when working with an exercise you'd want to make sure dart toolchain has it's cwd set to that exercise. Every exercise is an isolated dart package.

If we are going to disable the unused import rule, it'll have to apply to all the exercises and thus be in the top level as well as the exercise level. Otherwise, the exercises can drift apart and it'll be harder to tailor linting to all the exercises.

**Comment by devkabiir** [comment]
> If we are going to disable the unused import rule, it'll have to apply to all the exercises and thus be in the top level as well as the exercise level.

I understand, It does make sense to apply to all. I think we can do this slowly over time as needed. We can make do for now for the exercises that are getting updated.

> Otherwise, the exercises can drift apart and it'll be harder to tailor linting to all the exercises.

I don't understand this, care to elaborate?. In my mind at least, all exercises serve a unique value. Thus, they must be tailor made.

**Comment by kytrinyx** [comment]
This has been very helpful, thank you. I appreciate your patience, as I ramp up with the track and tools.

I now understand why this is happening, and what my options are.
I don't think we need to change the linting options—I just needed to understand how they all fit together.

I will spend a bit of time next week experimenting with a couple of different approaches, and will ask more questions if (when?) I hit more stumbling blocks.
