### ISSUE TITLE
A way to validate create-exercise tool

### ISSUE THREAD

**Issue by Stargator** [exercism/dart#52]
Our create-exercise tool is created in dart, but setup like a executable.

Even though it is getting love updates recently, there are no tests for it or ways to validate it works properly.

So I don't know if the best course of action would be to convert the file to a pure dart file so it would be run like `dart create_exercise.dart` since whoever wants to create a Dart implemented exercise should have Dart install. Then tests could be easily created.

Or if anyone has other ideas or thoughts.

**Comment by raphalvessa** [comment]
I don't see any harm in converting the file to a pure Dart file since, like you said, whoever's going to use it will already have the Dart SDK installed. However, instead of running it with `dart`, it would be cleaner to use `pub run` (but the user can use whichever command they prefer, as they'll produce the same result).

**Comment by kabiir** [comment]
@Stargator 
> but setup like a executable.  

This is kind of tricky on Windows, so I vote for running it with either `dart` or `pub run`. 
`pub run create-exercise` is the most simplest way if `create-exercise` exists inside of the` \bin` directory
I also suggest moving all future independent scripts in `\bin`

**Comment by Stargator** [comment]
I agree with moving independent scripts to bin/. I think I prefer running with `dart` as `pub run` seems a bit hit or miss with me

**Comment by kabiir** [comment]
@Stargator hit or miss? What do you mean? by default `pub run scriptname args` without `.dart` checks for a dart script in `bin/` and tries to execute it with provided arguments. It doesn't need any configuration.

**Comment by Stargator** [comment]
That hasn't been my experience. I try and run `pub run check_formatting` (the dart version) it gives an error and I want to avoid that kind of ambiguity for users. `dart filename.dart` is clear in how it's used.

**Comment by Stargator** [comment]
@kabiir As far as documentation goes, we could use `pub run` or `dart`, but either way I'd like us to be consistent.

It seems like a minor decision.

**Comment by kabiir** [comment]
@Stargator we can run test files with `dart` too. It'll make things easy and consistent. But idk if we should. `pub run` is essentially running `dart` underline. Thoughts?

**Comment by Stargator** [comment]
We're just talking about documentation, right? I prefer`dart` and will use it locally.  We could include a section that says that are the same, but that we'll use only one in the docs.

**Comment by kabiir** [comment]
@Stargator yes!, A two-liner section should suffice this. `pub run tests`  and `pub run scriptname` are darts standard ways of doing things. But `dart scriptname.dart`  is easier approach and will always work regardless of messy configuration, I think. However in both cases a `pubspec.yml` and a `.packages` is required which helps in resolving dependencies. Since we maintain our repo and make sure everything is always working on `master`  branch so this shouldn't be an issue.

**Comment by raphalvessa** [comment]
I really don't mind whichever one you guys think we should use, as long as it's easy and straightforward for everyone to use.

**Comment by Stargator** [comment]
#71 Addresses this, closing ticket.
